/* Generated by Yosys 0.46+124 (git sha1 8c2d1a16d, g++ 13.2.0-23ubuntu4 -fPIC -O3) */

module Full_Adder(a, b, cin, sum, cout);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  input a;
  wire a;
  input b;
  wire b;
  input cin;
  wire cin;
  output cout;
  wire cout;
  output sum;
  wire sum;
  INV_X1 _4_ (
    .A(cin),
    .ZN(_0_)
  );
  NAND2_X1 _5_ (
    .A1(a),
    .A2(b),
    .ZN(_1_)
  );
  NOR2_X1 _6_ (
    .A1(a),
    .A2(b),
    .ZN(_2_)
  );
  XOR2_X1 _7_ (
    .A(a),
    .B(b),
    .Z(_3_)
  );
  OAI21_X1 _8_ (
    .A(_1_),
    .B1(_2_),
    .B2(_0_),
    .ZN(cout)
  );
  XNOR2_X1 _9_ (
    .A(_0_),
    .B(_3_),
    .ZN(sum)
  );
endmodule

module RCA_32(a, b, cin, sum, cout);
  input [31:0] a;
  wire [31:0] a;
  input [31:0] b;
  wire [31:0] b;
  wire c1;
  wire c2;
  wire c3;
  input cin;
  wire cin;
  output cout;
  wire cout;
  output [31:0] sum;
  wire [31:0] sum;
  RCA_8 M0 (
    .a(a[7:0]),
    .b(b[7:0]),
    .cin(cin),
    .cout(c1),
    .sum(sum[7:0])
  );
  RCA_8 M1 (
    .a(a[15:8]),
    .b(b[15:8]),
    .cin(c1),
    .cout(c2),
    .sum(sum[15:8])
  );
  RCA_8 M2 (
    .a(a[23:16]),
    .b(b[23:16]),
    .cin(c2),
    .cout(c3),
    .sum(sum[23:16])
  );
  RCA_8 M3 (
    .a(a[31:24]),
    .b(b[31:24]),
    .cin(c3),
    .cout(cout),
    .sum(sum[31:24])
  );
endmodule

module RCA_4(a, b, cin, sum, cout);
  input [3:0] a;
  wire [3:0] a;
  input [3:0] b;
  wire [3:0] b;
  wire c1;
  wire c2;
  wire c3;
  input cin;
  wire cin;
  output cout;
  wire cout;
  output [3:0] sum;
  wire [3:0] sum;
  Full_Adder M0 (
    .a(a[0]),
    .b(b[0]),
    .cin(cin),
    .cout(c1),
    .sum(sum[0])
  );
  Full_Adder M1 (
    .a(a[1]),
    .b(b[1]),
    .cin(c1),
    .cout(c2),
    .sum(sum[1])
  );
  Full_Adder M2 (
    .a(a[2]),
    .b(b[2]),
    .cin(c2),
    .cout(c3),
    .sum(sum[2])
  );
  Full_Adder M3 (
    .a(a[3]),
    .b(b[3]),
    .cin(c3),
    .cout(cout),
    .sum(sum[3])
  );
endmodule

module RCA_8(a, b, cin, sum, cout);
  input [7:0] a;
  wire [7:0] a;
  input [7:0] b;
  wire [7:0] b;
  wire c1;
  input cin;
  wire cin;
  output cout;
  wire cout;
  output [7:0] sum;
  wire [7:0] sum;
  RCA_4 M0 (
    .a(a[3:0]),
    .b(b[3:0]),
    .cin(cin),
    .cout(c1),
    .sum(sum[3:0])
  );
  RCA_4 M1 (
    .a(a[7:4]),
    .b(b[7:4]),
    .cin(c1),
    .cout(cout),
    .sum(sum[7:4])
  );
endmodule
